import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import AsideBar from "@/components/account/AsideBar";
import { Page } from "@/models/Page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (!session) {
    return redirect("/");
  }
  const isGrabedUserName = await Page.findOne({ owner: session?.user?.email })
    .populate("bg_image")
    .populate("profile_image");

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          {isGrabedUserName ? (
            <>
              <aside className="bg-white w-64 p-4 shadow-2xl">
                <AsideBar imgSrc={session?.user?.image} />
              </aside>
            </>
          ) : (
            ""
          )}
          <div className="w-full h-full p-6">{children}</div>
        </main>
      </body>
    </html>
  );
}
