import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import AsideBar from "@/components/account/AsideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (!session) {
    return redirect("/");
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          <aside className="bg-white w-64 h-screen p-4 shadow-2xl">
            <AsideBar imgSrc={session?.user?.image} />
          </aside>
          <div className="max-w-4xl w-full p-6">{children}</div>
        </main>
      </body>
    </html>
  );
}
